# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-13 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
